<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <Version>1.1.1</Version>
        <AssemblyName>shadui-app</AssemblyName>
        <AssemblyTitle>ShadUI App</AssemblyTitle>
        <Product>ShadUI App</Product>
        <Company>AccounTech Business Management Services</Company>
        <Copyright>Copyright © ShadUI App 2025</Copyright>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
        <PrepareForRunDependsOn>$(PrepareForRunDependsOn);GenerateXamlTextCopies;GenerateCSharpTextCopies</PrepareForRunDependsOn>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.AvaloniaEdit"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="AvaloniaEdit.TextMate"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
<!--        <PackageReference Include="HotAvalonia" PrivateAssets="All"/>-->
        <PackageReference Include="Jab" PrivateAssets="All"/>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia"/>
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="TextMateSharp.Grammars"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ShadUI\ShadUI.csproj"/>
    </ItemGroup>

    <Target Name="GenerateXamlTextCopies" BeforeTargets="PrepareForRun">
        <ItemGroup>
            <XamlFiles Include="Views\**\*.axaml"/>
        </ItemGroup>

        <Copy SourceFiles="@(XamlFiles)"
              DestinationFiles="@(XamlFiles->'$(OutDir)views/%(RecursiveDir)%(Filename).axaml')"
              SkipUnchangedFiles="true"/>
    </Target>

    <Target Name="GenerateCSharpTextCopies" BeforeTargets="PrepareForRun">
        <ItemGroup>
            <CSharpFiles Include="ViewModels\**\*.cs" Exclude="ViewModels\ViewModelBase.cs"/>
        </ItemGroup>

        <Copy SourceFiles="@(CSharpFiles)"
              DestinationFiles="@(CSharpFiles->'$(OutDir)viewModels/%(RecursiveDir)%(Filename).cs')"
              SkipUnchangedFiles="true"/>
    </Target>
</Project>
