<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <Version>0.0.1</Version>
        <FileVersion>0.0.1</FileVersion>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageDescription>Avalonia-based Desktop UI Library inspired by shadcn and Suki UI Library</PackageDescription>
        <PackageTags>avalonia;avaloniaui;ui;theme;shadui</PackageTags>
        <PackageProjectUrl>https://github.com/accntech/shad-ui.git</PackageProjectUrl>
        <RepositoryUrl>https://github.com/accntech/shad-ui.git</RepositoryUrl>
        <PackageIcon>icon.png</PackageIcon>
        <Authors>accntech</Authors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Skia" />
        <PackageReference Include="MinVer"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Themes.Simple" />
    </ItemGroup>

    <PropertyGroup>
        <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Controls\ContentExpandControl.axaml.cs">
        <DependentUpon>ContentExpandControl.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Lucide.Avalonia">
        <HintPath>C:\Users\DearVa\.nuget\packages\lucide.avalonia\0.1.30\lib\net8.0\Lucide.Avalonia.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
